name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install

    - name: Check if .env file exists
      run: test -f .env || cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Migrate database
      run: php artisan migrate --env=testing --force

    - name: Run tests
      run: ./vendor/bin/pest || echo "Tests success" && exit 1

    - name: Send email on failure
      if: ${{ failure() }}
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_APP_PASSWORD }}   # Use the application-specific password here
        subject: 'Tests Failed on Your Project'
        body: 'Your tests have failed. Check the CI logs for details.'
        to: chanleang7779@gmail.com
        from: your-email@example.com


